server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
        - id: serie-service
          uri: lb://serie-service
          predicates:
            - Path=/series/**

  security:
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: 749141560336-lb7i5k1bohi8e0kp2qg10vj783hlhss0.apps.googleusercontent.com
            client-secret: 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
            scope: openid
            redirect_uri: http://localhost:8080/login/oauth2/code/google

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway