server:
  port: ${PORT:${SERVER_PORT:0}}

idRandom: ${random.value}

spring:
  application:
    name: catalog-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog
  
    rabbitmq:
      username: guest
      password: guest
      host: localhost
      port: 5672

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/