server:
  port: ${PORT:${SERVER_PORT:0}}

idRandom: ${random.value}

spring:
  application:
    name: movie-service

  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/moviedev
      username: root
      password: 123456

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/